config_dict = {
    "action": {
        "lateral": True,
        "longitudinal": False, # to True if acceleration wanted
        'target_speeds': [0, 5, 10],
        "type": "ContinuousAction",
    },
    "action_reward": -0.1,
    "centering_position": [0.5, 0.5],
    "collision_reward": -10,
    "controlled_vehicles": 1,
    "duration": 300,
    "lane_centering_cost": 4,
    'lane_centering_reward': 1,
    'manual_control': False,
    "observation": {
        "align_to_vehicle_axes": True,
        "as_image": False,
        "features": ['presence', 'on_road'],
        "grid_size": [[-18, 18], [-18, 18]],
        "grid_step": [3, 3],
        "type": "OccupancyGrid",
    },
    "offscreen_rendering": True,
    "other_vehicles": 7,
    "other_vehicles_type": "highway_env.vehicle.behavior.IDMVehicle",
    "policy_frequency": 5,
    'real_time_rendering': False,
    "render_agent": True,
    "scaling": 7,
    "screen_height": 600,
    "screen_width": 600,
    "show_trajectories": True,
    "simulation_frequency": 15,
}